config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :invitations => 'users/invitations', 
    :registrations => 'users/registrations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  namespace :admin, path: '/', constraints: { subdomain: 'admin' }  do
    resources :books
    resources :discounts

    root :to => 'books#index', as: :admin_root
  end

  authenticated :user do
    root :to => 'library#index', as: :authenticated_root
  end
  root 'home#landing'
  get 'about', to: 'home#about'
  get 'how_it_works', to: 'home#how_it_works'
  get 'press', to: 'home#press'
  get 'pricing', to: 'home#pricing'
  get 'privacy', to: 'home#privacy'
  get 'testimonials', to: 'home#testimonials'
  get 'landing', to: 'home#landing'
  get 'jobs', to: 'home#jobs'
  get 'publishers', to: 'home#publishers'
  get 'affiliates', to: 'home#affiliates'
  get 'disclaimer', to: 'home#disclaimer'

  resources :users, only: [:show, :destroy, :update] do
    member do
      get :edit
    end
    collection do
      put :set_session_close_info
    end
  end

  constraints Constraint::BookUrlConstrainer.new do
    get '/:id', to: 'books#show', as: :book
  end
  resources :books, except: :show do
    member do
      put :pick
      put :read
      put :pocket
      put :kindle
      get :content
    end
  end

  resources :library

  resources :subscriptions do
    collection do
      put :update
      put :pay
      get :promotion
    end
  end

  resources :discount do
    collection do
      put :take
    end
  end

  resources :categories, controller: :tags, only: [:index, :show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :books, only: [:index, :landing]
  before_action :plans, only: [:pricing]

  def pricing
  end

  def landing
    @books = Book.all.limit(8).order("RANDOM()")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.slim
body.about  
  .cms__static__teaser_about
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 About Blinkist
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element_active
          = link_to 'About Blinkist', about_path
        li.cms__static__teaser__menu-element
          = link_to 'Press', press_path
        li.cms__static__teaser__menu-element
          = link_to 'Jobs', jobs_path
        li.cms__static__teaser__menu-element
          a href = "http://support.blinkist.com/hc" target = "_blank"  Contacts
      select#select.cms__static__teaser__menu_select name="select"
        option value="/about"  About Blinkist   
        option value="/press"  Press
        option value="/jobs"  Jobs
        option value="http://support.blinkist.com/hc"  Contacts
  .cms__blocks__container
    .cms__blocks__header
      h2 Five things to know about Blinkist
      p.cms__blocks__separator-line
    .cms__blocks__paragraph-container
      h3 1. With Blinkist, you always have time to read.
      p
        | We believe that great knowledge should be easily accessible to anyone, anytime. But between work, personal
        | life, social life, and studies, finding time to read is tough. We want to change all of that with blinks:
        | a new format that lets you learn deeply, wherever you are, in whatever time you have.
    .cms__blocks__paragraph-container
      h3 2. Fast, profound learning is a blink’s specialty.
      p
        | Blinks are powerful bites of insight from outstanding nonfiction. You can read a blink in less than two
        | minutes, so with each book made up of about eight blinks, you can cover the work’s key insights in 15 minutes.
    .cms__blocks__paragraph-container
      h3 3. Your reading goes anywhere, on any device.
      p
        | Smartphones and tablets have rapidly changed how and where we read, so we made blinks with mobile in mind.
        | Our apps were designed to give you the clearest, most beautiful reading experience, whether you’re using
        | Blinkist on your iPhone, iPad, or the web.
  .cms__blocks__testimonial-bar
    .cms__blocks__testimonial-bar__slogan-container
      .cms__blocks__testimonial-bar__slogan
        h2 "Instead of needing to trawl the web for new knowledge, it's all there in one easy place."
        p Brad Couper
  .cms__blocks__container
    .cms__blocks__paragraph-container
      h3 4. Blinks aren’t meant to replace books – and we’d never want them to.
      p
        | Blinks are made to be brief, so their very format keeps them from filling a book’s formidable (if imaginary)
        | shoes. We think of Blinkist the way that Neil Degrasse Tyson does 
        a href="http://www.google.com/url?q=http%3A%2F%2Fwww.brainpickings.org%2Findex.php%2F2013%2F09%2F05%2Fneil-degrasse-tyson-on-the-art-of-the-soundbite%2F&sa=D&sntz=1&usg=AFQjCNHUb1ukzTTK-gwpgcJ3CBF73Ab7ww" target="_blank"
          | a soundbite 
        | as the beginning of a self-driven path toward learning. Get your bearings with Blinkist, then take your
        | learning in whichever direction you choose.
    .cms__blocks__paragraph-container
      h3 5. Our Blinks are 100% original works.
      p
        | We start from scratch every time. Bright, inquisitive readers and writers dive deep into the books we
        | blink in order to create thoughtful new content that imparts the original work’s key messages and intent.
    p.cms__blocks__separator-line
    .cms__blocks__bottom-cta
      h2 You were born curious. Start learning now.
      p
        | Sign up to try Blinkist for 3 days, free.
        br/
        | You’ll get access to our whole library on any device,
        br/
        | whether you’re online or off.
      a.button href=new_user_registration_path  Start my 3-day trial
  

app/views/home/affiliates.html.slim
body.affiliates  
  .cms__static__teaser_partners
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 Partners
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element
          = link_to 'Publishers', publishers_path
        li.cms__static__teaser__menu-element.cms__static__teaser__menu-element_active
          = link_to 'Affiliate Programs', affiliates_path
      select#select.cms__static__teaser__menu_select name="select" 
        option value="/affiliates"  Affiliate Program
        option value="/publishers"  Publishers
        
  .cms__blocks__container
    .cms__blocks__header
      h2 Affiliate Program
      p.cms__blocks__separator-line
    .cms__blocks__paragraph-container
      h3 Join the Blinkist Affiliate Program
      p
        | Do you have a blog, mailing list, or otherwise enormous army of followers? Then we've got something smart for
        | you. With the Blinkist Affiliate Program, you can earn commission by referring your readers and followers to
        | Blinkist. And we're confident it's great for your audience, too: people love Blinkist, so they'll thank you
        | for
        | introducing them to this powerful new way to learn.
    .cms__blocks__header
      h2 Your advantages:
      p.cms__blocks__separator-line
    .cms__blocks__paragraph-container
      h3 1. Attractive commission
      p
        | We offer various commission schemes from one-time payouts for sign-ups and sales to long-term revenue share
        | models.
    .cms__blocks__paragraph-container
      h3 2. Value for your readers through smart advertising
      p
        | Blinkist is very popular among readers and lifelong learners. Does that sound like the readers of your blog
        | or mailing list, too? Right! That’s why Blinkist is the perfect product to advertise and recommend.
    .cms__blocks__paragraph-container
      h3 3. High conversion among all platforms
      p
        | Blinkist's browser-based app works for anyone, no matter which device they're using. Native apps for iOS,
        | Android and Kindle boost retention and long-term revenue.
    p.cms__blocks__separator-line
    .cms__blocks__bottom-cta
      h2 Ready to share something great? Become a Blinkist Affiliate Partner!
      a.button href="http://affiliate.blinkist.com" target="_blank"  Sign up now
  

app/views/home/how_it_works.html.slim
body.making__a__blinks
  .cms__static__teaser_how_it_works
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 How it works
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element_active
          = link_to 'Making a Blink', how_it_works_path
        li.cms__static__teaser__menu-element
          = link_to 'Plans & Pricing', pricing_path
        li.cms__static__teaser__menu-element
          = link_to 'User stories', testimonials_path
      select#select.cms__static__teaser__menu_select name="select"
        option value="/how_it_works" Making a Blink
        option value="/pricing" Plans & Pricing
        option value="/testimonials" User stories
  .cms__blocks__container
    .cms__blocks__header
      h2 Making a Blink
      p.cms__blocks__separator-line
    .cms__blocks__paragraph-container_custom-width
      h3 Great books. Smart people. No algorithms.
      p
        | We comb bestseller lists, review user suggestions, and solicit thought leader input to find the most intriguing
        | reads out there. Next, our readers and writers dive into the selected texts and surface with the most valuable
        | insights from each work. The resulting blinks are proofread and lovingly polished by human hands. By the time a
        | book in blinks makes it to you, we trust that it is a skillfully, mindfully made bundle of mind-changing
        | insights – and you can, too.
    p.cms__blocks__separator-line
    .cms__blocks__features__features-external-container
      .cms__blocks__features__features-container
        .cms__blocks__features__feature-bookmark
          .cms__blocks__features__feature-bookmark__graphic
          .cms__blocks__features__feature-bookmark__title
            | 1. Find a book's most important insights
        .cms__blocks__features__feature-note
          .cms__blocks__features__feature-note__graphic
          .cms__blocks__features__feature-note__title
            | 2. Create a structure that brings the key ideas to light
        .cms__blocks__features__feature-laptop
          .cms__blocks__features__feature-laptop__graphic
          .cms__blocks__features__feature-laptop__title
            | 3. Unify it all with clear, thoughtful writing
    p.cms__blocks__separator-line
    .cms__blocks__bottom-cta
      h2 You were born curious. Start learning now.
      p
        | Sign up to try Blinkist for 3 days, free.
        br/
        | You’ll get access to our whole library on any device,
        br/
        | whether you’re online or off.
      a.button href=new_user_registration_path  Start my 3-day trial


  

app/views/home/index.html.slim
.container
  .dynamic-grid__container data-url="/blinks" style=("position: relative; height: 3051.9059524536133px;") 
    .dynamic-grid__element-size
    .dynamic-grid__element-gutter
      - @books.each do |book|
        = render 'books/book', book: book

app/views/home/jobs.html.slim
body.jobs  
  .cms__static__teaser_about
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 About Blinkist
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element
          = link_to 'About Blinkist', about_path
        li.cms__static__teaser__menu-element
          = link_to 'Press', press_path
        li.cms__static__teaser__menu-element_active
          = link_to 'Jobs'
        li.cms__static__teaser__menu-element
          a href = "http://support.blinkist.com/hc" target = "_blank"  Contacts
      select#select.cms__static__teaser__menu_select name="select"
        option value="/jobs"  Jobs
        option value="/about" About Blinkist
        option value="/press" Press
        option value="http://support.blinkist.com/hc"  Contacts
  .cms__blocks__container
    .cms__blocks__header
      h2 Jobs
      p.cms__blocks__separator-line
      .cms__blocks__paragraph-container_full-width
        p
          | We believe that reading enlivens minds, sparks passion, and helps us be better humans. Our mission is to
          | give curious minds what they yearn for: great knowledge from great books, made just for how modern readers
          | like to learn. Come help us make it happen!
      p.cms__blocks__separator-line
    .cms__blocks__paragraph-container_horizontal
      .cms__pages__jobs__paragraph-container_with-icons
        .cms__pages__jobs__paragraph-icon__map
        h3 Freedom rules
        p
          | Our strategic plan is called getting things done. Whatever work style lets you give your best,
          | we offer you the trust and the independence to do it.
      .cms__pages__jobs__paragraph-container_with-icons
        .cms__pages__jobs__paragraph-icon__cloud
        h3 Down with hierarchy!
        p
          | At Blinkist, we have responsibilities, not rank. You’ll have your own projects and your own realms of
          | expertise in which you (yep, you!) call the shots.
    .cms__blocks__paragraph-container_horizontal
      .cms__pages__jobs__paragraph-container_with-icons
        .cms__pages__jobs__paragraph-icon__fire
        h3 Feed the fire
        p
          | Whether it’s a crunchy snack, a new book, or an educational opportunity, we fuel what you burn for.
          | With weekly learning sessions and hackathons, you’ll never be without inspiration.
      .cms__pages__jobs__paragraph-container_with-icons
        .cms__pages__jobs__paragraph-icon__space-warrior
        h3 Celebrate &amp; unwind
        p
          | Great work deserves to be rewarded – and the people behind it should be, too! From meditation lessons to
          | milestone parties, we make room for wellness and fun, too.
    p.cms__blocks__separator-line
    .cms__blocks__container
      .cms__pages__jobs__paragraph-container_button
        .cms__pages__jobs__paragraph-container_button-top
          h3 Senior Android Developer
          p.cms__static__paragraph-container_location-paragraph 
            |(Berlin, Germany)
        .cms__pages__jobs__paragraph-container_button-content
          p
            | We are looking for a top-notch Android developer to help us make Blinkist one of the greatest Android apps.
            | The Blinkist Android app is fully native, our minSdkVersion is 16 and we build our app using Gradle,
            | RxJava, Dagger, GitHub and a bunch of other great tools. We have been featured in the Play Store and are
            | committed to deliver an experience that truly fits the platform.
            | Join us and help us shape the future of nonficition reading &amp; mobile learning!
        a.button href="mailto:jobs@blinkist.com?subject=Senior Android Developer"  Apply here
    .cms__blocks__bottom-cta
      h4
        | Got something special to add to the team? We want to hear about it!
        a href="mailto:jobs@blinkist.com"  Write us
        |  a message and say hello.
  

app/views/home/press.html.slim
body.press
  .cms__static__teaser_about
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 About Blinkist
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element
          = link_to 'About Blinkist', about_path
        li.cms__static__teaser__menu-element_active
          = link_to 'Press', press_path
        li.cms__static__teaser__menu-element
          = link_to 'Jobs', jobs_path
        li.cms__static__teaser__menu-element
          a href = "http://support.blinkist.com/hc" target = "_blank"  Contacts
      select#select.cms__static__teaser__menu_select name="select"
        option value="/press" Press
        option value="/about" About Blinkist
        option value="/jobs"  Jobs
        option value="http://support.blinkist.com/hc"  Contacts
  .cms__blocks__container
    .cms__blocks__header
      h2 Press
      p.cms__blocks__separator-line
    .cms__pages__press__paragraph-container_inline-block_right
      h3 Get in touch
      p
        | Write to us at
        a href="mailto:press@blinkist.com"  press@blinkist.com
    .cms__pages__press__paragraph-container_inline-block
      h3 About Blinkist
      p
        | Blinkist is a mobile learning company that distills key insights from outstanding nonfiction books into
        | fifteen-minute, made-for-mobile reads. Our mission is to make great knowledge engaging, inspiring, and
        | accessible for the modern reader. Based in Berlin, Blinkist has been serving curious minds since 2013
        | and is currently available for iPhone, iPad and web.
    .cms__blocks__paragraph-container
      h3 Blinkist at a Glance
      ul
        li Launched: January 2013
        li User count: 100,000+
        li Founders: Holger Seim, Niklas Jansen, Tobias Balling, Sebastian Klein
        li Team count: 14
        li Headquarters: Berlin, Germany
        li Languages offered: English, German
        li Available for: iPhone, iPad, web
        li Number of books in blinks: 250
  .cms__blocks__testimonial-bar
    .cms__blocks__testimonial-bar__slogan-container
      .cms__blocks__testimonial-bar__slogan
        h2 "Blinkist solves the modern reading problem by putting great nonfiction in 15-minute packs."
  .cms__blocks__container
    .cms__blocks__paragraph-container_full-width
      h3 Blinkist in the Media
      section.cms__blocks__table
        .cms__blocks__table-row
          .cms__blocks__table-cell 14.11.2011
          .cms__blocks__table-cell_bold TechCrunch
          .cms__blocks__table-cell
            a href="http://techcrunch.com/2013/11/14/blinkist-book-summaries-arrive-to-improve-your-commute-and-make-you-look-smart/" target="_blank"  "Blinkist Book Summaries Arrive to Improve Your Commute And Make You Look Smart"
        .cms__blocks__table-row
          .cms__blocks__table-cell 29.11.2013
          .cms__blocks__table-cell_bold Lifehacker
          .cms__blocks__table-cell
            a href="http://lifehacker.com/blinkist-summarizes-important-parts-of-books-for-quick-1473108833/all" target="_blank"  "The summaries are actually pretty great"
        .cms__blocks__table-row
          .cms__blocks__table-cell 16.1.2014
          .cms__blocks__table-cell_bold TheNextWeb
          .cms__blocks__table-cell
            a href="http://thenextweb.com/apps/2014/01/16/blinkist/" target="_blank"  "No time to read? Blinkist wants to help."
        .cms__blocks__table-row
          .cms__blocks__table-cell 21.3.2014
          .cms__blocks__table-cell_bold Forbes
          .cms__blocks__table-cell
            a href="http://www.forbes.com/sites/kathycaprino/2014/03/21/what-the-greatest-self-help-books-of-the-last-decades-can-teach-you-in-7-minutes/" target="_blank"  "Blinkist offers a terrific service – great ideas distilled down to their very essence"
    .cms__pages__press__paragraph-container_wide
      h3 Media Material
      p The Founders
      .cms__pages__press__media__images-container
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Founders/Gruender.jpg" target="_blank" 
            img alt="Team" height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/team-5301519c96519c0cca7ef8bcb8b15c2e.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Founders/Holger-Seim.jpg" target="_blank" 
            img alt="Holger" height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/holger-80d07767943e037dc88b071b7438f032.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Founders/Niklas-Jansen.jpg" target="_blank" 
            img alt="Niklas" height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/niklas-737a6a2e2c129220a83ef8872afdd73c.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Founders/Tobias-Balling.jpg" target="_blank" 
            img alt="Tobi" height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/tobi-5fa486154a805f2d59919d4c96e7fbd4.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Founders/Sebastian-Klein.jpg" target="_blank" 
            img alt="Sebastian" height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/sebastian-34f002de80b5310794d90b95f3d31561.jpg" widht="180" /
      p Logos
      .cms__pages__press__media__images-container
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Logo/Blinkist-Logo_White.png" target="_blank" 
            img alt=("Blinkist logo white") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist-Logo_White-8f0a8b4ad3d20f80eeb5db6509b97f7a.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Logo/Blinkist-Logo_Black.png" target="_blank" 
            img alt=("Blinkist logo black") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist-Logo_Black-c7bdb51a5d5a9e5ac4198c8dbd19ab68.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Icon/Blinkist-Icon-White.png" target="_blank" 
            img alt=("Blinkist icon white") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist-Icon-White-b070079ad07a33724af2a871b1e50337.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Icon/Blinkist-Icon-Black.png" target="_blank" 
            img alt=("Blinkist icon black") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist-Icon-Black-6fface40fb6f897fc0a6487f17185bbf.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Icon/Blinkist-App-Icon.png" target="_blank" 
            img alt=("Blinkist app icon") height="130" src="/assets/Blinkist-App-Icon.jpg" widht="180" /
      p Product Shots
      .cms__pages__press__media__images-container
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPad-1-en.png" target="_blank" 
            img alt=("Ipad 1 en") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/iPad-1-en-4e4e5420e901090c3d771df6fbfb6786.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPad-2-en.png" target="_blank" 
            img alt=("Ipad 2 en") height="130" src="/assets/iPad-2-en.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPad-3-en.png" target="_blank" 
            img alt=("Ipad 3 en") height="130" src="/assets/iPad-3-en.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPad-4-en.png" target="_blank" 
            img alt=("Ipad 4 en") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/iPad-4-en-9fb78d23fa652c242147ea74062522e8.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPhone5-1-en.png" target="_blank" 
            img alt=("Iphone5 1 en") height="130" src="/assets/iPhone5-1-en-2b788f98713a9b6fbc4b65040fe48bb1.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPhone5-2-en.png" target="_blank" 
            img alt=("Iphone5 2 en") height="130" src="/assets/iPhone5-2-en.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPhone5-2-en.png" target="_blank" 
            img alt=("Iphone5 3 en") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/iPhone5-3-en-8447afd1d1fb31b7b6f7389c9f2a9823.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/iPhone5-4-en.png" target="_blank" 
            img alt=("Iphone5 4 en") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/iPhone5-4-en-6b6859ea9ec9b17e699ce39bd898eab0.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/Blinkist2-03.png" target="_blank" 
            img alt=("Blinkist2 03") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist2-03-eac4993bb46e9fa6b273dd153477b6f5.jpg" widht="180" /
        .cms__pages__press__media__image-container
          a href="http://static.blinkist.com/documents/Press_Page_New/Product_Shots/Ambient/Blinkist2-06.png" target="_blank" 
            img alt=("Blinkist2 06") height="130" src="https://db0his2obn5eo.cloudfront.net/assets/cms/pages/press/Blinkist2-06-bceb39ecbd3859dbf7e3a75a1b23a1fc.jpg" widht="180" /
  

app/views/home/pricing.html.slim
body.pricing
  .cms__static__teaser_how_it_works
    .cms__static__teaser__content-container
      .cms__static__teaser__content
        h1 How it works
      ul.cms__static__teaser__menu
        li.cms__static__teaser__menu-element
          = link_to 'Making a Blink', how_it_works_path
        li.cms__static__teaser__menu-element_active
          = link_to 'Plans & Pricing', pricing_path
        li.cms__static__teaser__menu-element
          = link_to 'User stories', testimonials_path
  .cms__blocks__container
    .cms__blocks__header
      h2 Plans &amp; Pricing
      p.cms__blocks__separator-line
    .cms__pages__plans-container
      - @plans.each do |plan|
        .cms__pages__plans__plan-container
          p = plan.name
          .cms__pages__plans__plan__price-container
            .cms__pages__plans__plan__price-number
              = plan.price.to_s.split('.')[0]
            .cms__pages__plans__plan__price-currency
              = plan.price.to_s.split('.')[1]
          .shared__purchase-button-container
            button.shared__purchase-button data-action="subscribe" data-default-text="Choose" name="button" type="button"  Choose
    p.cms__blocks__separator-line_without-margin
    .cms__pages__plans__paragraph-container_horizontal_with-margin
      .cms__pages__plans__paragraph-container_half-width
        h3 Can I test Blinkist before I subscribe?
        p
          | Of course you can! We want you to get to know Blinkist and what it’s like to use our service before you
          | commit. Just sign up and you’ll get 3 free days of unlimited access to our library, no strings attached.
      .cms__pages__plans__paragraph-container_half-width
        h3 What do I get when I subscribe?
        p
          | You can expect at least 40 new books landing in the library every month. Plus, you’ll get fancy new
          | features and feature improvements designed to make reading and remembering the key lessons from nonfiction
          | books even easier.
    .cms__pages__plans__paragraph-container_horizontal_with-margin
      .cms__pages__plans__paragraph-container_half-width
        h3 Can I buy gift cards or group licenses?
        p
          | Yes! If you want to buy a gift card or purchase Blinkist for a group of people or an organization,
          | get in touch with us at
          a href="mailto:hello@blinkist.com"  hello@blinkist.com
      .cms__pages__plans__paragraph-container_half-width
        h3 How can I pay?
        p You can pay with any major credit card either on our website or through an iTunes In-App Purchase.
    .cms__pages__plans__paragraph-container_horizontal_with-margin
      .cms__pages__plans__paragraph-container_half-width
        h3 Is there a cancellation period?
        p
          | Our subscriptions are auto-renewable, but you can cancel your subscription anytime up until 24 hours
          | before the next renewal. We’d never want you to pay for something you don’t like or use, so we’ll
          | send you a reminder before renewal happens.
      .cms__pages__plans__paragraph-container_half-width
        h3 Can I switch plans?
        p
          | If you’d like to switch subscription periods, say, from a monthly to a yearly plan in order to save money,
          | just cancel your first subscription when it turns out and re-subscribe for the new duration.
          | Don’t worry, we’ll save your reading stats!