config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :invitations => 'users/invitations', 
    :registrations => 'users/registrations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  namespace :admin, path: '/', constraints: { subdomain: 'admin' }  do
    resources :books
    resources :discounts

    root :to => 'books#index', as: :admin_root
  end

  authenticated :user do
    root :to => 'library#index', as: :authenticated_root
  end
  root 'home#landing'
  get 'about', to: 'home#about'
  get 'how_it_works', to: 'home#how_it_works'
  get 'press', to: 'home#press'
  get 'pricing', to: 'home#pricing'
  get 'privacy', to: 'home#privacy'
  get 'testimonials', to: 'home#testimonials'
  get 'landing', to: 'home#landing'
  get 'jobs', to: 'home#jobs'
  get 'publishers', to: 'home#publishers'
  get 'affiliates', to: 'home#affiliates'
  get 'disclaimer', to: 'home#disclaimer'

  resources :users, only: [:show, :destroy, :update] do
    member do
      get :edit
    end
    collection do
      put :set_session_close_info
    end
  end

  constraints Constraint::BookUrlConstrainer.new do
    get '/:id', to: 'books#show', as: :book
  end
  resources :books, except: :show do
    member do
      put :pick
      put :read
      put :pocket
      put :kindle
      get :content
    end
  end

  resources :library

  resources :subscriptions do
    collection do
      put :update
      put :pay
      get :promotion
    end
  end

  resources :discount do
    collection do
      put :take
    end
  end

  resources :categories, controller: :tags, only: [:index, :show]
end

app/models/library.rb
class Library < ActiveRecord::Base
  belongs_to :user
  
  has_many :librarians
  has_many :books, -> { uniq }, through: :librarians
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  before_action :authenticate_user!
  before_action :library, only: [:index]

  def index
    filtered_books
  end  
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/views/library/_index.html.slim
body.index__index.inside
  .container
    .dynamic-grid__container data-url="/library" style=("position: relative; height: 661.249927520752px;") 
      .dynamic-grid__element-size
      .dynamic-grid__element-gutter
      - if !close_info
        .notification__trial-started.dynamic-grid__element.alert style=("position: absolute; left: 0px; top: 0px;") role="alert"
          .notification__trial-started__image
            img height="130" src=asset_path('trial_started.png') width="125" 
          .notification__trial-started__text
            .notification__trial-started__title = t('.trial_started')
            p = t('.trial_info')
          = link_to t('.ok'), set_session_close_info_users_path, method: :put, class: 'button button__green info-close', remote: true
      - elsif current_user.subscription.plan.is_trial?
        - if current_user.subscription.actived?
          .dynamic-grid__element.notification__trial-expiring style="position: absolute; left: 0px; top: 0px;"
            .notification__trial-expiring__cta
              .notification__trial-expiring__image
                img height="130" src=asset_path('trial_expiring.png') width="125" 
              .notification__trial-expiring__text
                .notification__trial-expiring__title = t('.trial_expiring_title', days: distance_of_time_in_words_to_now(current_user.subscription.expires_on))
                p = t('.trial_expiring_info')
                button.button.grey data-action="dismiss-dialog" data-action-url=".notification__trial-expiring" type="button" = t('.continue_trial')
                a.button.green href="#" = t('.upgrade_now')
            .notification__trial-expiring__referral
              .notification__trial-expiring__title = t('.trial_referral_title')
              p = t('.trial_referral_info')
              = link_to t('.trial_referral_invite'), new_user_invitation_path, remote: true, class: 'button grey'
        - else
          .notification__trial-started.dynamic-grid__element.alert style=("position: absolute; left: 0px; top: 0px;") role="alert"
            .notification__trial-expired__image
              img height="130" src=asset_path('trial_expired.png') width="125" 
            .notification__trial-expired__text
              .notification__trial-expired__title = t('.trial_expired_title')
              p
                = t('.trial_expired_info')
              = link_to t('.subscribe_now'), subscriptions_path, remote: true, class: 'button green'
      
      - if @books.count == 0
        p.no-books-message
          = raw t('.no_books', link: link_to(t('.here'), books_url))
      - else
        - @books.each  do |book|
          .blink.dynamic-grid__element style=("position: absolute; left: 0px; top: 251px;") 
            = link_to content_book_path(book) do
              .blink__image
                img src=book.cover.url(:thumb)
              .blink__text
                .blinks-pack__text__author = book.author
                .blinks-pack__text__title
                  = book.title
                .blinks-pack__text__description lang="en" 
                  p style=("overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 6;") 
                    = book.recommend
              .blink__button.add-to-library style="display:block" 
                a.button.add-to-library data-toggle="modal" data-target="#send-to-pocket-modal" data-pocket-url=pocket_book_url(book)
                  = t('.send_to_pocket')
              - if current_user.kindle.presence
                .blink__button.add-to-library style="display:block" 
                  = link_to t('.send_to_kindle'), { :controller => 'books', :action => 'kindle', :id => book.id }, { :class => 'button add-to-library', :method => :put, :remote => true }

  = render 'send_to_pocket_modal'
  = render 'load_pocket_form.js.erb'

app/views/library/_load_pocket_form.js.erb
<script>
  $('#send-to-pocket-modal').on('show.bs.modal', function (e) {
    var url = $(e.relatedTarget).data('pocket-url');
    $('form#pocket', this).attr('action', url);
  })

  $('#send-to-pocket-modal form#pocket input[type=submit]').on('click', function (e) {
    $('#send-to-pocket-modal').modal('hide');
  })
</script>

app/views/library/_menu.html.slim
ul.libray-menu__container
  li.top-menu__item.active
    = link_to t('.currently_reading'), library_index_path(filter: :unread), remote: true
  li.top-menu__item
    = link_to t('.finished'), library_index_path(filter: :read), remote: true

app/views/library/_send_to_pocket_modal.html.slim
.modal.fade#send-to-pocket-modal aria-hidden="true" aria-labelledby="mySmallModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button" 
            span aria-hidden="true"  &times;
          h4.modal-title Pocket email
      = form_for Book.new, :url => '', :html => { :method => :put, :remote => true, id: 'pocket' } do |f|
        .modal-body
          input type="email" name="pocket_email"
        .modal-footer
          = f.submit t('.submit')
        

app/views/library/index.html.slim
= render 'library/index'

app/views/library/index.js.erb
$('.create__library__header__container').remove();

$("main").html("<%= escape_javascript(render 'library/index') %>");

if (!$('.libray-menu__container').length) {
  $("main").before("<%= escape_javascript(render 'library/menu') %>");
}

window.msnry = new Masonry(".dynamic-grid__container", {
  columnWidth: 258,
  itemSelector: '.dynamic-grid__element'
});

$('.libray-menu__container .top-menu__item a').on('click', function(e) {
  $('.libray-menu__container .top-menu__item').removeClass('active');
  $(this).parent().addClass('active');
});