config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { 
    :invitations => 'users/invitations', 
    :registrations => 'users/registrations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  namespace :admin, path: '/', constraints: { subdomain: 'admin' }  do
    resources :books
    resources :discounts

    root :to => 'books#index', as: :admin_root
  end

  authenticated :user do
    root :to => 'library#index', as: :authenticated_root
  end
  root 'home#landing'
  get 'about', to: 'home#about'
  get 'how_it_works', to: 'home#how_it_works'
  get 'press', to: 'home#press'
  get 'pricing', to: 'home#pricing'
  get 'privacy', to: 'home#privacy'
  get 'testimonials', to: 'home#testimonials'
  get 'landing', to: 'home#landing'
  get 'jobs', to: 'home#jobs'
  get 'publishers', to: 'home#publishers'
  get 'affiliates', to: 'home#affiliates'
  get 'disclaimer', to: 'home#disclaimer'

  resources :users, only: [:show, :destroy, :update] do
    member do
      get :edit
    end
    collection do
      put :set_session_close_info
    end
  end

  constraints Constraint::BookUrlConstrainer.new do
    get '/:id', to: 'books#show', as: :book
  end
  resources :books, except: :show do
    member do
      put :pick
      put :read
      put :pocket
      put :kindle
      get :content
    end
  end

  resources :library

  resources :subscriptions do
    collection do
      put :update
      put :pay
      get :promotion
    end
  end

  resources :discount do
    collection do
      put :take
    end
  end

  resources :categories, controller: :tags, only: [:index, :show]
end

app/models/book.rb
class Book < ActiveRecord::Base
  include PgSearch
  extend FriendlyId

  friendly_id :title, use: :slugged
  pg_search_scope :search_full_text, :against => [
    :title,
    :recommend,
    :keys,
    :lessons
  ]

  acts_as_taggable

  has_many :librarians
  has_many :libraries, through: :librarians

  has_attached_file :cover, 
    :styles => { 
      :full => "128x128>", 
      :thumb => "107x107#" 
    }, 
    :default_url => lambda { |a| "#{a.instance.create_default_url}" },
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
    :url => ":s3_domain_url",
    :path => "/:class/covers/:id_:basename.:style.:extension"

  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  validates :title, uniqueness: true

  def should_generate_new_friendly_id?
    new_record? || slug.blank?
  end

  def create_default_url
    ActionController::Base.helpers.asset_path("missing-cover.png")
  end

  def s3_credentials
    { 
      :bucket => ENV['BUCKET'], 
      :access_key_id => ENV['AWS_S3_KEY'], 
      :secret_access_key => ENV['AWS_S3_SECRET'] 
    }
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::SuperusersController
  before_action :books, only: [:index]
  before_action :book, only: [:edit, :update, :destroy]
  before_action :create_book, only: [:create]

  load_and_authorize_resource
  
  def index
  end

  def new
  end

  def create
    if @book.save
      books && flash[:notice] = t('books.create.success')
    else
      flash[:error] = t('books.create.failure')
    end
  end

  def edit
    @book.summary = ReverseMarkdown.convert @book.summary
  end

  def update
    if @book.update_attributes(book_params)
      books && flash[:notice] = t('books.update.success')
    else
      flash[:error] = t('books.update.failure')
    end
  end

  def destroy
    if @book.destroy
      books && flash[:notice] = t('books.destroy.success')
    else
      flash[:error] = t('books.destroy.failure')
    end
  end

  private
  def book
    @book = Book.find(params[:id])
  end

  def create_book
    @book = Book.new(book_params)
  end

  def book_params
    ['keys', 'lessons'].each do |arr|
      params[:book][arr] = params[:book][arr][0].split('|') unless params[:book][arr].nil?
    end

    params[:book][:summary] = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new, extensions = {}).render(params[:book][:summary])

    params.require(:book).permit(:title, :author, :cover, :recommend, :summary, :tag_list, :keys => [], :lessons => [])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :books, only: [:index]
  before_action :book, only: [:pick, :content, :read, :show, :pocket, :kindle]
  before_action :librarian, only: [:read]
  before_action :read_now?, only: [:content]

  after_action :track_pick_book, only: [:pick]
  after_action :track_read_book, only: [:read]

  rescue_from CanCan::AccessDenied do |exception|
    if action_name.eql?('kindle') || action_name.eql?('pocket') 
      response.headers['X-Message'] = URI::encode t('books.limit')
      response.headers["X-Message-Type"] = 'danger'

      render :nothing => true, :status => 401
    end
  end
  
  def index
    respond_to do |format|
      format.html
      format.json { render json: @books }
    end
  end

  def show
  end

  def pick
    authorize! :pick, @book
    
    current_user.library.books.push(@book)
    render :update
  end

  def content
    authorize! :read, @book

    @content = @book.summary
    render layout: false
  end

  def read
    authorize! :read, @book
    
    @librarian.read
    redirect_to library_index_path
  end

  def pocket
    authorize! :pocket, @book
    
    begin
      UsersMailer.send_to_pocket(params[:pocket_email], content_book_url(@book)).deliver_now!
      current_user.add_pocket
      flash[:notice] = t('books.send_to_pocket.success')
      
      render :nothing => true, :status => 200
    rescue
      flash[:error] = t('books.send_to_pocket.failure')
      render :nothing => true, :status => 500
    end
  end

  def kindle
    authorize! :kindle, @book
    
    begin
      UsersMailer.send_to_kindle(current_user.kindle, @book).deliver
      current_user.add_kindle
      flash[:notice] = t('books.send_to_kindle.success')
      
      render :nothing => true, :status => 200
    rescue
      flash[:error] = t('books.send_to_kindle.failure')
      render :nothing => true, :status => 500
    end
  end

  private
  def book
    @book = Book.friendly.find(params[:id])
  end

  def librarian
    @librarian = current_user.library.librarians.find_by(book: @book)
  end

  def read_now?
    if(!can?(:read, @book) && can?(:pick, @book))
      current_user.library.books.push(@book)
    end
  end

  def track_pick_book
    return unless ENV['SEGMENT_IO_KEY']
    Analytics.track(
      user_id: current_user.id,
      event: 'Book added',
      properties: {
        title: @book.title,
        category: @book.tags.map(&:name).join(','),
        author: @book.author
    })
  end

  def track_read_book
    return unless ENV['SEGMENT_IO_KEY']
    Analytics.track(
      user_id: current_user.id,
      event: 'Book finished',
      properties: {
        title: @book.title,
        category: @book.tags.map(&:name).join(','),
        author: @book.author
    })
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def action(user, book)
    return content_tag :div, class: 'blink__button subscribe-now', style: 'display:block' do
      link_to I18n.t('books.index.subscribe_now'), subscriptions_path, { remote: true, :class => 'button subscribe-now' }
    end unless user.subscription.actived?
    
    unless user.library.books.include?(book)
      content_tag :div, class: 'blink__button add-to-library', style: 'display:block' do
        link_to I18n.t('books.index.add_to_library'), { :controller => 'books', :action => 'pick', :id => book.id }, { :class => 'button add-to-library', :method => :put, :remote => true }
      end
    else
      content_tag :div, class: 'blink__button already-in-library', style: 'display:block' do
        content_tag :button, I18n.t('books.index.in_your_library'), class: 'button already-in-library', disabled: "disabled", name: "button", type:"submit"
      end
    end
  end
end

app/views/books/_book.html.slim
.blink.dynamic-grid__element data-id=book.id style=("position: absolute; left: 0px; top: 0px;") 
  = link_to book_path(book), remote: true do
    .blink__image
      img src=book.cover.url(:thumb) 
    .blink__text.remove__bottom-border
      .blinks-pack__text__author
        = book.author
      .blinks-pack__text__title
        = book.title
      .blinks-pack__text__description lang="en" 
        p style=("overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 6;") 
          = book.recommend
    - if user_signed_in?
      = action(current_user, book)

app/views/books/_show.html.slim
article.product__container lang="en" 
  .product__container-content
    .product__top__container
      .product__top__container__left
        .product__info
          p.product__title-authorName = @book.author
          h1.product__title-subTitle = @book.title
          p
            = @book.recommend
        .product__info__buttons
          .product__info__buttons__left
            - if user_signed_in?
              = link_to t('.read_now'), content_book_path(@book), class: 'read-now-button'
            - else
              = link_to t('.sign_up'), new_user_registration_path(), class: 'read-now-button'
      .product__top__container__right
        img.product__image src=@book.cover.url(:full)
    .product__middle__container
      .product__info__bar
        .product__info__bar__item
          - unless @book.tags.empty?
            .product__info__bar__item.categories
              - @book.tags.each do |tag|
                = link_to tag.name, category_path(tag)
                = "&nbsp;".html_safe
      div
        h4 = t('.keys')
        ul
          - @book.keys.each do |key|
            li = key
      .product__middle__content
        h4 = t('.lessons')
        ul
          - @book.lessons.each do |lesson|
            li = lesson

app/views/books/content.html.slim
doctype html
html.no-js lang="en" 
  head
    title = @book.title
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
  body style="background-color:white"
    .reader__container__left
      .reader__container__menu_bar
        span.close
          = link_to '', library_index_path, class: 'reader__close-icon'
    .reader__container__right
      .shared__reader__blink.reader__container__content
        .chapter.chapter_visible style="display: block;"
          h1
            = @book.title
          = raw @content.html_safe
          .reader__container__buttons
            .pull-left
              = social_share_button_tag(@book.title, :popup => "true")
            .reader__container__navigation_control
              .reader__container__navigation_control__prev_button style=""
                = link_to '', read_book_url(@book), { class: 'reader__finish-icon', method: :put }
                
    = javascript_include_tag 'application'

app/views/books/index.html.slim
body.welcome__index.inside
  - if current_user.sign_in_count == 1
    .create__library__header__container
      .create__library__header
        .create__library__header__left
          p.create__library__headline = t('.library_headline')
          p.create__library__sub-headline = t('.library_sub_headline')
        .create__library__header__right
          = link_to t('.continue'), discount_index_path, class: 'button continue-to-library', disabled: true

  .container
    .dynamic-grid__container data-url="/welcome" style=("position: relative; height: 3639.7496948242188px;")
      .dynamic-grid__element-size
      .dynamic-grid__element-gutter
      - @books.each do |book|
        = render 'book', book: book

app/views/books/show.html.slim
= render 'show'

app/views/books/show.js.erb
$('.libray-menu__container').remove();

$("main").html("<%= escape_javascript(render 'show') %>");

app/views/books/update.js.erb
$('div[data-id="<%= @book.id %>"]').replaceWith("<%= escape_javascript(render 'book', book: @book) %>");
window.msnry.appended($('div[data-id="<%= @book.id %>"]'));
window.msnry.layout();